### ISSUE TITLE
Troubles with applying 

### ISSUE THREAD

**Issue by ghost** [szorfein/dots#1]
Got this. OS: Zorin. Awesomewm already installed. What can i do?

bogdan@laptop:~/.temp$ chezmoi apply
$--------------------------------------------------$
$-->$ Execute /tmp/611334996.1-init.sh... $

bogdan ALL=(ALL) NOPASSWD: /bin/systemctl poweroff
bogdan ALL=(ALL) NOPASSWD: /bin/systemctl reboot
bogdan ALL=(ALL) NOPASSWD: /bin/systemctl restart tor

$-->$ End for /tmp/611334996.1-init.sh $
$--------------------------------------------------$
$--------------------------------------------------$
$-->$ Execute /tmp/775018147.10-install-packages.sh... $

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package firefox-esr is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'firefox-esr' has no installation candidate
chezmoi: exit status 100

**Comment by szorfein** [comment]
Yep debian and ubuntu are a little different, principaly in package name and version.  Unfortunately, I have no plan (and time) to add/test support for Ubuntu based distro (or RPM distro, etc), people are free to contribute to add support for their favorite distro :)

But if you want, you can try to edit script for install, i think you should only edit:
+ run_once_10-install-packages.sh.tmpl : correct package name  (like here with `firefox` or `firefox-bin` rather than `firefox-esr`).

And maybe:
+ run_once_20-extra-deps.sh.tmpl 

All other script should work, Do a `chezmoi apply` when you're finish to correct and look if it work :+1: 

You can even remove firefox from the script, it's not stricly necessary.
