### ISSUE TITLE
Feature - doas for suported OS

### ISSUE THREAD

**Issue by TheRealOne78** [szorfein/dots#15]
Most of gentoo users use doas instead of sudo because it's less bloated. It would be nice something like
```
if (/bin/doas)
$ROOT_PREV = doas;
else if (/bin/sudo)
$ROOT_PREV = sudo;
else()
print("No root instalation method");
```
or something like this. I think that arch distros have doas as well.

**Comment by szorfein** [comment]
I didn't know doas, i'm going to test this and we'll see, thank you :)

**Comment by Ariimeow78** [comment]
After 1 year of using gentoo and doas, I came to a conclusion that sudo is good enough.
I guess that installing the doas package would be nice, however it can't be used for configuration files since doas needs the user to prompt the password everytime doas runs.
Chezmoi would use doas a lot and that means the user would have to input the password porbably more than 50 times!

I'd also advise not to support gentoo anymore since gentoo is a bleeding-edge distro that needs to be re-configured every time something updates. The gentoo repository is always updated and most of the updates will have breaking changes such as new/deleted/renamed use flags and conflicts.
I'd love emerge to be automated, but it's simply not possible since portage is supposed to be human-operated, unlike other package managers such as pacman or dpkg.
